"""add apiary_locations environmental_data lab_results tables and apiary_id harvest_date quantity to honey_batches

Revision ID: 50c45b379e24
Revises: 5ea90ce8c2fb
Create Date: 2026-05-15 14:43:41.740601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c45b379e24'
down_revision: Union[str, Sequence[str], None] = '5ea90ce8c2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiary_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('vegetation_type', sa.String(), nullable=True),
    sa.Column('hive_count', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: GeoAlchemy2 auto-creates the GiST index on the `location` column
    # at table-create time, so an explicit `idx_apiary_locations_location`
    # CREATE INDEX would duplicate-fail.
    op.create_index(op.f('ix_apiary_locations_id'), 'apiary_locations', ['id'], unique=False)
    op.create_index(op.f('ix_apiary_locations_latitude'), 'apiary_locations', ['latitude'], unique=False)
    op.create_index(op.f('ix_apiary_locations_longitude'), 'apiary_locations', ['longitude'], unique=False)
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('weather_source', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_environmental_data_id'), 'environmental_data', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('moisture_content', sa.Float(), nullable=True),
    sa.Column('sucrose_level', sa.Float(), nullable=True),
    sa.Column('hmf_level', sa.Float(), nullable=True),
    sa.Column('pollen_density', sa.Float(), nullable=True),
    sa.Column('purity_score', sa.Float(), nullable=True),
    sa.Column('passed_quality_check', sa.Boolean(), nullable=True),
    sa.Column('laboratory_name', sa.String(), nullable=True),
    sa.Column('analyst_name', sa.String(), nullable=True),
    sa.Column('certificate_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    # NOTE: autogenerate proposed dropping `otps`, `spatial_ref_sys`, and
    # `aggregators.wallet_address` — all preserved here. `spatial_ref_sys` is
    # PostGIS-owned; `otps` and aggregator wallet drops are deferred cleanup.
    op.add_column('farmers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('farmers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('honey_batches', sa.Column('apiary_id', sa.Integer(), nullable=True))
    op.add_column('honey_batches', sa.Column('harvest_date', sa.DateTime(), nullable=True))
    op.add_column('honey_batches', sa.Column('quantity', sa.Float(), nullable=True))
    op.alter_column('honey_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'honey_batches', 'apiary_locations', ['apiary_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'honey_batches', type_='foreignkey')
    op.alter_column('honey_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('honey_batches', 'quantity')
    op.drop_column('honey_batches', 'harvest_date')
    op.drop_column('honey_batches', 'apiary_id')
    op.drop_column('farmers', 'updated_at')
    op.drop_column('farmers', 'created_at')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_environmental_data_id'), table_name='environmental_data')
    op.drop_table('environmental_data')
    op.drop_index(op.f('ix_apiary_locations_longitude'), table_name='apiary_locations')
    op.drop_index(op.f('ix_apiary_locations_latitude'), table_name='apiary_locations')
    op.drop_index(op.f('ix_apiary_locations_id'), table_name='apiary_locations')
    op.drop_table('apiary_locations')
    # ### end Alembic commands ###
