"""add eth_wallets table and wallet_address columns

Revision ID: 5ea90ce8c2fb
Revises: cf8e61b0da77
Create Date: 2026-04-07 09:40:04.510425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea90ce8c2fb'
down_revision: Union[str, Sequence[str], None] = 'cf8e61b0da77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('blockchain_role', sa.String(), nullable=True),
    sa.Column('role_granted', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('role_tx_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eth_wallets_id'), 'eth_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_eth_wallets_wallet_address'), 'eth_wallets', ['wallet_address'], unique=True)
    op.add_column('aggregators', sa.Column('wallet_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'aggregators', ['wallet_address'])
    op.add_column('farmers', sa.Column('wallet_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'farmers', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farmers', type_='unique')
    op.drop_column('farmers', 'wallet_address')
    op.drop_constraint(None, 'aggregators', type_='unique')
    op.drop_column('aggregators', 'wallet_address')
    op.drop_index(op.f('ix_eth_wallets_wallet_address'), table_name='eth_wallets')
    op.drop_index(op.f('ix_eth_wallets_id'), table_name='eth_wallets')
    op.drop_table('eth_wallets')
    # ### end Alembic commands ###
