"""add honey_batches table

Revision ID: cf8e61b0da77
Revises: ad730960cdbd
Create Date: 2026-04-07 09:18:09.049936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8e61b0da77'
down_revision: Union[str, Sequence[str], None] = 'ad730960cdbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honey_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_batch_id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('apiary_data', sa.JSON(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('harvest_data', sa.JSON(), nullable=True),
    sa.Column('process_data', sa.JSON(), nullable=True),
    sa.Column('lab_proof_data', sa.JSON(), nullable=True),
    sa.Column('packaging_data', sa.JSON(), nullable=True),
    sa.Column('distribution_data', sa.JSON(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('create_tx_hash', sa.String(), nullable=True),
    sa.Column('harvest_tx_hash', sa.String(), nullable=True),
    sa.Column('process_tx_hash', sa.String(), nullable=True),
    sa.Column('lab_verify_tx_hash', sa.String(), nullable=True),
    sa.Column('packaging_tx_hash', sa.String(), nullable=True),
    sa.Column('distribution_tx_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('harvested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('lab_verified_at', sa.DateTime(), nullable=True),
    sa.Column('packaged_at', sa.DateTime(), nullable=True),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_batches_blockchain_batch_id'), 'honey_batches', ['blockchain_batch_id'], unique=True)
    op.create_index(op.f('ix_honey_batches_id'), 'honey_batches', ['id'], unique=False)
    # NOTE: spatial_ref_sys is a PostGIS system table — do NOT drop it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_honey_batches_id'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_blockchain_batch_id'), table_name='honey_batches')
    op.drop_table('honey_batches')
    # ### end Alembic commands ###
