"""add geo_ai_predictions and validation_results tables

Sprint 12 — off-chain GeoAI provenance authentication. Two new tables that hold
the ML prediction (expected lab chemistry for a claimed place+time) and the
validation outcome (predicted vs actual lab metrics -> authenticity_score).
Hash-neutral: neither table feeds a canonical *_records payload or a keccak256
anchor, so /verify and 6-state determinism are unaffected.

Hand-authored (NOT autogenerated): the schema has PostGIS Geography columns +
GiST indexes elsewhere, and teammate-owned tables had model drift, so
--autogenerate would have emitted spurious spatial ops and DROP COLUMNs.

Revision ID: d1e2f3a4b5c6
Revises: c0d1e2f3a4b5
Create Date: 2026-06-05
"""
from alembic import op
import sqlalchemy as sa


revision = "d1e2f3a4b5c6"
down_revision = "c0d1e2f3a4b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # geo_ai_predictions first — validation_results FKs it.
    op.create_table(
        "geo_ai_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("predicted_moisture", sa.Float(), nullable=True),
        sa.Column("predicted_sugar", sa.Float(), nullable=True),
        sa.Column("predicted_hmf", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("region_detected", sa.String(), nullable=True),
        sa.Column("flowering_species", sa.String(), nullable=True),
        sa.Column("triangulation_score", sa.Float(), nullable=True),
        sa.Column("flora_match_score", sa.Float(), nullable=True),
        sa.Column("dist_to_zone_km", sa.Float(), nullable=True),
        sa.Column("n_flowering_species", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["honey_batches.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id"),
    )
    op.create_index(
        "ix_geo_ai_predictions_id", "geo_ai_predictions", ["id"], unique=False
    )

    op.create_table(
        "validation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("authenticity_score", sa.Float(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("validation_status", sa.String(), nullable=True),
        sa.Column("phys_match_score", sa.Float(), nullable=True),
        sa.Column("triangulation_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["honey_batches.id"]),
        sa.ForeignKeyConstraint(["prediction_id"], ["geo_ai_predictions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id"),
    )
    op.create_index(
        "ix_validation_results_id", "validation_results", ["id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_validation_results_id", table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_index("ix_geo_ai_predictions_id", table_name="geo_ai_predictions")
    op.drop_table("geo_ai_predictions")
